---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400
- name: Update the repository cache and update package "nginx" to latest version using default release squeeze-backport
  apt:
    name: nginx
    state: latest
    default_release: squeeze-backports
    update_cache: yes

- name: Add repository
  apt_repository
    repo: 'deb http://nginx.org/packages/debian/ {{ansible_distribution_release}} nginx' 
    state: present
    update_cache: yes

- name: Ensure nginx is installed.
  apt:
    name: "{{ nginx_package_name }}"
    state: installed
    default_release: "{{ nginx_default_release }}"
