---
- name: Remove any obsolete scripts used by an old version of the role
  file: path={{ item }} state=absent
  with_items:
    - /etc/network/if-post-down.d/iptables-v4
    - /etc/network/if-pre-up.d/iptables-v4
    - /etc/iptables.v4.saved

- name: Install iptables-persistent
  apt: name=iptables-persistent state=present

- name: Check if netfilter-persistent is present
  shell: which netfilter-persistent
  register: is_netfilter
  when: v4_script|changed or v6_script|changed
  changed_when: false
  ignore_errors: yes

- name: Save v4 rules (netfilter-persistent)
  command: netfilter-persistent save
  when: v4_script|changed and is_netfilter.rc == 0

- name: Save v4 rules (iptables-persistent)
  command: /etc/init.d/iptables-persistent save
  when: v4_script|changed and is_netfilter.rc == 1

- name: Save v6 rules (netfilter-persistent)
  command: netfilter-persistent save
  when: v6_script|changed and is_netfilter.rc == 0

- name: Save v6 rules (iptables-persistent)
  command: /etc/init.d/iptables-persistent save
  when: v6_script|changed and is_netfilter.rc == 1


