---
# If 127.0.0.1 is a system resolver when dnsmasq is running, all on-box
#  queries are answered with the local wlan ip address. This breaks apt
#  updates and other stuff that needs a working resolver. This tells
#  resolvconf to avoid setting 127.0.0.1 as a nameserver in /etc/resolv.conf
# This doesn't affect our ability to answer queries from wlan in the way
#  that we wish to i.e. answer everything with the local address
# This blacklisting task must be before dnsmasq is installed (or somehow
#  the blacklisting isn't applied immediately)
- name: Blacklist 127.0.0.1 as a nameserver for the system resolver
  lineinfile:
    dest: /etc/resolvconf.conf
    line: name_server_blacklist=127.0.0.1
    state: present

- name: Install dnsmasq
  apt:
    name: dnsmasq
    state: present

- name: Copy dnsmasq configuration
  template:
    src: etc_dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: 0644
    validate: dnsmasq --test --conf-file=%s
  notify: Reload dnsmasq

- name: Start and enable dnsmasq
  service:
    name: dnsmasq
    enabled: yes
    state: started
